// Action types
export const SET_GAME_STATE = "SET_GAME_STATE";
export const SELECT_WAIFU = "SELECT_WAIFU";
export const SET_MOOD = "SET_MOOD";
export const SET_AFFECTION = "SET_AFFECTION";
export const INC_AFFECTION = "INC_AFFECTION";
export const DEC_AFFECTION = "DEC_AFFECTION";
export const SET_CURRENT_IMAGE = "SET_CURRENT_IMAGE";
export const SET_DIALOGUE = "SET_DIALOGUE";
export const SET_CHOICES = "SET_CHOICES";
export const ADD_HISTORY = "ADD_HISTORY";
export const INC_CONVERSATION_COUNT = "INC_CONVERSATION_COUNT";
export const SET_LOADING = "SET_LOADING";
export const TOGGLE_SOUND = "TOGGLE_SOUND";
export const TOGGLE_MUSIC = "TOGGLE_MUSIC";
export const SET_SETTINGS_VISIBLE = "SET_SETTINGS_VISIBLE";
export const SET_CURRENT_MUSIC_REF = "SET_CURRENT_MUSIC_REF";
export const SET_SELECTED_MUSIC_TRACK = "SET_SELECTED_MUSIC_TRACK";
export const SET_GREETING_IMAGE = "SET_GREETING_IMAGE";
export const UNLOCK_OUTFIT = "UNLOCK_OUTFIT";
export const SET_CURRENT_OUTFIT = "SET_CURRENT_OUTFIT";
export const ADD_SCREENSHOT = "ADD_SCREENSHOT";
export const ADD_GIFT = "ADD_GIFT";
export const SET_CURRENT_DATE_COUNT = "SET_CURRENT_DATE_COUNT";
export const SET_DATE_LOCATION = "SET_DATE_LOCATION";
export const SET_MINIGAME = "SET_MINIGAME";
export const RESET_MINIGAME_RUNTIME = "RESET_MINIGAME_RUNTIME";
export const SET_MINIGAME_RUNTIME = "SET_MINIGAME_RUNTIME";
export const ADD_MEMORY = "ADD_MEMORY";
export const SET_THEME = "SET_THEME";
export const SET_STORY_PROGRESS = "SET_STORY_PROGRESS";
export const ADD_UNLOCKED_ENDING = "ADD_UNLOCKED_ENDING";
export const SET_ACHIEVEMENTS = "SET_ACHIEVEMENTS";
export const BULK_UPDATE_FROM_ADMIN = "BULK_UPDATE_FROM_ADMIN";
export const SET_ADMIN_PANEL_VISIBLE = "SET_ADMIN_PANEL_VISIBLE";
export const RESET_GAME = "RESET_GAME";
export const SET_CONVERSATION_COUNT = "SET_CONVERSATION_COUNT";

// Action creators
export const setGameState = (state) => ({ type: SET_GAME_STATE, payload: state });
export const selectWaifu = (waifuKey) => ({ type: SELECT_WAIFU, payload: waifuKey });
export const setMood = (mood) => ({ type: SET_MOOD, payload: mood });
export const setAffection = (value) => ({ type: SET_AFFECTION, payload: value });
export const incAffection = (value) => ({ type: INC_AFFECTION, payload: value });
export const decAffection = (value) => ({ type: DEC_AFFECTION, payload: value });
export const setCurrentImage = (url) => ({ type: SET_CURRENT_IMAGE, payload: url });
export const setDialogue = (text) => ({ type: SET_DIALOGUE, payload: text });
export const setChoices = (choices) => ({ type: SET_CHOICES, payload: choices });
export const addHistory = (entry) => ({ type: ADD_HISTORY, payload: entry });
export const incConversationCount = () => ({ type: INC_CONVERSATION_COUNT });
export const setLoading = (loading) => ({ type: SET_LOADING, payload: loading });
export const toggleSound = () => ({ type: TOGGLE_SOUND });
export const toggleMusic = () => ({ type: TOGGLE_MUSIC });
export const setSettingsVisible = (visible) => ({ type: SET_SETTINGS_VISIBLE, payload: visible });
export const setCurrentMusicRef = (ref) => ({ type: SET_CURRENT_MUSIC_REF, payload: ref });
export const setSelectedMusicTrack = (index) => ({ type: SET_SELECTED_MUSIC_TRACK, payload: index });
export const setGreetingImage = (url) => ({ type: SET_GREETING_IMAGE, payload: url });
export const unlockOutfit = (outfitId) => ({ type: UNLOCK_OUTFIT, payload: outfitId });
export const setCurrentOutfit = (outfitId) => ({ type: SET_CURRENT_OUTFIT, payload: outfitId });
export const addScreenshot = (screenshot) => ({ type: ADD_SCREENSHOT, payload: screenshot });
export const addGift = (gift) => ({ type: ADD_GIFT, payload: gift });
export const setCurrentDateCount = (count) => ({ type: SET_CURRENT_DATE_COUNT, payload: count });
export const setDateLocation = (location) => ({ type: SET_DATE_LOCATION, payload: location });
export const setMinigame = (gameId) => ({ type: SET_MINIGAME, payload: gameId });
export const resetMinigameRuntime = () => ({ type: RESET_MINIGAME_RUNTIME });
export const setMinigameRuntime = (runtime) => ({ type: SET_MINIGAME_RUNTIME, payload: runtime });
export const addMemory = (memory) => ({ type: ADD_MEMORY, payload: memory });
export const setTheme = (themeId) => ({ type: SET_THEME, payload: themeId });
export const setStoryProgress = (progress) => ({ type: SET_STORY_PROGRESS, payload: progress });
export const addUnlockedEnding = (ending) => ({ type: ADD_UNLOCKED_ENDING, payload: ending });
export const setAchievements = (achievements) => ({ type: SET_ACHIEVEMENTS, payload: achievements });
export const bulkUpdateFromAdmin = (updates) => ({ type: BULK_UPDATE_FROM_ADMIN, payload: updates });
export const setAdminPanelVisible = (visible) => ({ type: SET_ADMIN_PANEL_VISIBLE, payload: visible });
export const resetGame = () => ({ type: RESET_GAME });
export const setConversationCount = (count) => ({ type: SET_CONVERSATION_COUNT, payload: count });
